msaconfig:
  ipaddress: "192.168.11.1"
  dbtype: "oracle"
---
spring:
  profiles: local

msaconfig:
  ipaddress: "192.168.11.2"
  dbtype: "mysql"
  
---
spring:
  profiles: dev

msaconfig:
  ipaddress: "192.168.11.3"
  dbtype: "nosql"
---
